GET http://localhost:3000/products?page=3&limit=10
###
GET http://localhost:3000/products/8894
###
GET http://localhost:3000/products/new 
###
POST http://localhost:3000/products/create
Content-Type: application/json

{
    "name": "Ordenador",
    "price": 120,
    "stock": 10,
    "available": true
}